# Generated by Django 3.2.4 on 2021-06-27 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_nme', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='date_begin')),
                ('adress', models.CharField(max_length=300)),
                ('organizer', models.CharField(default='Центр космоэенргетики "Анаэль"', max_length=200)),
                ('phone_num1', models.CharField(default='+7 961 595-02-20', max_length=25)),
                ('phone_num2', models.CharField(max_length=25)),
                ('seo_keywords', models.CharField(max_length=250)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('cosmoenergy', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=5)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminars', to='seminars.city')),
            ],
            options={
                'ordering': ('-date_begin',),
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='seminars.region'),
        ),
    ]
